spring:
  datasource:
    url: jdbc:postgresql://db:5432/cab_db
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/cab-realm/protocol/openid-connect/certs
          issuer-uri: http://localhost:8081/realms/cab-realm

keycloak:
  auth-server-url: http://keycloak:8080